"""adicionadas tabelas grupo_um e grupo_dois

Revision ID: c807fdf05d57
Revises: 
Create Date: 2022-02-17 15:15:09.088214

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c807fdf05d57"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grupo_um",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("idade", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "grupo_dois",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("idade", sa.Integer(), nullable=False),
        sa.Column("conjuge_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conjuge_id"],
            ["grupo_um.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("grupo_dois")
    op.drop_table("grupo_um")
    # ### end Alembic commands ###
